### PR TITLE
Navigation hot keys

### PR DESCRIPTION
**Pull request by azhurauski-sc**
Key combination is `alt` + `key for tab`

### CODE REVIEW

**Comment by skylarrichard123** [comment]
Doesn't seem to be working for me. Mac alt = option, correct?

**Review by ndemidovich-sc — APPROVED** [review]

**Comment by azhurauski-sc** [comment]
> Doesn't seem to be working for me. Mac alt = option, correct?

It doesn't work in browser window for me as well.

**Comment by azhurauski-sc** [comment]
> Doesn't seem to be working for me. Mac alt = option, correct?

As I saw on the pictures, yes

**Comment by skylarrichard123** [comment]
If we can't override that or come up with an alternative short-key, then we should just consider removing for now. This isn't a very important feature and I think there's more important things to focus on. Let me know what you think.

**Comment by azhurauski-sc** [comment]
> 

ok

**Pull request closed without merging**
