### PR TITLE
Update mnemonic phrase flow

### PR DESCRIPTION
**Pull request by azhurauski-sc**
depends on https://github.com/iron-fish/ui-kit/pull/107
link to design
https://www.figma.com/file/fYw3aNgfS0qCS2jezGqv8P/Wallet-(New-Ui-Kit)?node-id=4623%3A19922&t=yv5V6oY07jPNGUKk-1

### CODE REVIEW

**Comment by azhurauski-sc** [comment]
@skylarrichard123 please also check create account button on `Privacy accounts` page

**Comment by skylarrichard123** [comment]
I can't get past the confirm mnemonic phrase screen lol. It won't let me proceed. 

I entered the correct phrase but the create account button remains disabled.

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
We shouldn't show an error after the first character is typed in the re-enter mnemonic seed phrase component. 

We should wait to show an error until the user clicks outside of the component.

**Comment by skylarrichard123** [comment]
https://user-images.githubusercontent.com/75860817/218486465-c03dbcda-1221-4676-a337-9fd336c22867.mov

**Comment by azhurauski-sc** [comment]
> We shouldn't show an error after the first character is typed in the re-enter mnemonic seed phrase component.
> 
> We should wait to show an error until the user clicks outside of the component.

Updated

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
Screen Shot 2023-02-15 at 1 11 38 PM
Should have spaces between the words here, "Copy to clipboard" clipboard one word.

**Review by skylarrichard123 — APPROVED** [review]

**Review by dgca — APPROVED** [review]

**Pull request merged**
