### PR TITLE
Added possibility to export account.

### PR DESCRIPTION
**Pull request by ndemidovich-sc**
Added possibility to export account from Account Details - Keys Tab.
Changes:
- Hidden Mnemonic Phrase view component
- Added Spending, Incoming and Outgoing keys preview

> **NOTE!** Behavior of Export Account button is different in application and browser.
In application after click open dialog with possibility to choose save file path.

### CODE REVIEW

**Review by azhurauski-sc — APPROVED** [review]

**Comment by skylarrichard123** [comment]
Why did we remove the mnemonic phrase? I think I' missing some context?

**Comment by azhurauski-sc** [comment]
> Why did we remove the mnemonic phrase? I think I' missing some context?

As we can't use it for import or for other things, it was hidden.

**Comment by skylarrichard123** [comment]
Why can't we use it for import?

**Comment by skylarrichard123** [comment]
Seems to work well

**Pull request merged**
