### PR TITLE
IRO-2093 - Added Receive money page.

### PR DESCRIPTION
**Pull request by ndemidovich-sc**

### CODE REVIEW

**Comment by azhurauski-sc** [comment]
Please merge staging in this branch its to much changes in diff.

**Comment by skylarrichard123** [comment]
Assuming this isn't ready for review?

**Comment by azhurauski-sc** [comment]
@skylarrichard123 my comment just related to code not how the page look, so it can be reviewed.

**Comment by ndemidovich-sc** [comment]
> Please merge staging in this branch its to much changes in diff.

Done.

**Review by azhurauski-sc — APPROVED** [review]

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
https://linear.app/ironfish/issue/IRO-2477/receive-dollariron

**Comment by azhurauski-sc** [comment]
Update @skylarrichard123 please have a look.

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
https://linear.app/ironfish/issue/IRO-2093/receive-money-page
two sub tasks added

**Review by skylarrichard123 — APPROVED** [review]

**Pull request merged**
