### PR TITLE
Fixed filters and sorts.

### PR DESCRIPTION
**Pull request by ndemidovich-sc**

### CODE REVIEW

**Comment by skylarrichard123** [comment]
is search supposed to be working in this branch?

**Comment by ndemidovich-sc** [comment]
> is search supposed to be working in this branch?

Yes

**Comment by skylarrichard123** [comment]
What are the search parameters?

**Comment by ndemidovich-sc** [comment]
> What are the search parameters?

- Accounts (`name`, `publicAddress`)
- Transactions (`from`, `to` addresses, `memo`)
- Address book (`name`, `address`)

**Comment by skylarrichard123** [comment]
From the branch in the link above
Accounts: Name search doesn't seem to work
Txn: none of the paramaters seem to work
Address Book: When I type a search input, and then delete the input, the page goes blank

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
see comments above

**Comment by skylarrichard123** [comment]
Update: search is case sensitive, we are changing that.

**Comment by skylarrichard123** [comment]
What's been updated?

**Comment by azhurauski-sc** [comment]
> What's been updated?

>Address Book: When I type a search input, and then delete the input, the page goes blank
was fixed, other stuff seems to work as needed, all searches are left case sensitive

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
Accounts page: it doesn't seem like searching by account names works that well. The first letters of the account names work, but adding a second results in 0 search results. 

Account activity: 
- I think $IRON amount should be searchable

**Comment by skylarrichard123** [comment]
If we're going to remove search from the accounts page we can just ignore that comment

**Review by skylarrichard123 — APPROVED** [review]

**Pull request merged**
