### PR TITLE
Autocomplete update behavior

### PR DESCRIPTION
**Pull request by azhurauski-sc**

### CODE REVIEW

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
1- if the contact doesnt have a saved name, then the x icon doesnt show up when you click outside the field

2- I think our address hash will be 32 or 43 characters, I forgot, but when I have that answer we should make it so when a user tries to paste in a hash that's too long or too short, we allow them to enter that input, but we also show an error saying the hash is too long or too short and disable the send. I'll get a design ready in Jan.

**Comment by azhurauski-sc** [comment]
At the moment our addresses are 64 characters long and if input is not 64 characters long it will be ignored, will not be counted as an item. You try this one `ab27b3ee5f689ed6a73bfd7e3c282c325e67793b0ff0bdb3b57188c918ed0f53`

**Comment by azhurauski-sc** [comment]
> 1- if the contact doesnt have a saved name, then the x icon doesnt show up when you click outside the field
> 
> 2- I think our address hash will be 32 or 43 characters, I forgot, but when I have that answer we should make it so when a user tries to paste in a hash that's too long or too short, we allow them to enter that input, but we also show an error saying the hash is too long or too short and disable the send. I'll get a design ready in Jan.

Seem that public address is 64 characters length.

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
We still need to fix this:  if the contact doesnt have a saved name, then the x icon doesnt show up when you click outside the field

Added an image below of how to handles errors when a user inputs a public address that is either too long or too short.

**Comment by skylarrichard123** [comment]
Screen Shot 2023-01-03 at 2 44 19 PM

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
I'll need to wait to review this until the backend requirements for the character count is changed because there's an error no matter what I do.

**Comment by azhurauski-sc** [comment]
Revert key length back to 64 as I'm not sure that it should be 43.

**Comment by skylarrichard123** [comment]
https://user-images.githubusercontent.com/75860817/211577413-8066dfe0-46a9-40a1-ba73-27a309656360.mov

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
see video attachment

**Comment by azhurauski-sc** [comment]
> see video attachment

Fixed, also not sure that it will be possible to create account without name now 🙂

**Review by ndemidovich-sc — APPROVED** [review]

**Review by skylarrichard123 — APPROVED** [review]

**Pull request merged**
