### PR TITLE
Added add contact to send flow.

### PR DESCRIPTION
**Pull request by azhurauski-sc**
https://airtable.com/appIXmGgVqP9QdbCf/tblAWSTOQbTq6vh6X/viwDHZiWCwtbVXlQ1/recm4IhbGo0dyap6w?blocks=hide

### CODE REVIEW

**Review by ndemidovich-sc — APPROVED** [review]

**Comment by skylarrichard123** [comment]
I can't attempt to test this because the syncing never completes on this branch

**Comment by azhurauski-sc** [comment]
@skylarrichard123 improved synchronization speed, let me know if its need to be faster or slower

**Comment by azhurauski-sc** [comment]
The address should be 86 characters length, otherwise its not counted as valid
`pjqETg9UDzCmE9QSuWwrNO80NC9GNYtLWwyHhw0slynI1lRi9NS3BX_sD8yWtk7DWwyHhw0slynI1lRi9NS3Bs`

**Comment by skylarrichard123** [comment]
Screen Shot 2022-12-02 at 10 42 54 AM

**Comment by skylarrichard123** [comment]
This fee of 7e-8 $IRON is a confusing in my opinion. I have zero idea what that means

**Comment by azhurauski-sc** [comment]
> This fee of 7e-8 $IRON is a confusing in my opinion. I have zero idea what that means

Updated

**Pull request merged**
