### PR TITLE
Added possibility to autoupdate of application

### PR DESCRIPTION
**Pull request by ndemidovich-sc**
### Autoupdate in application

Autoupdate functionality is provided by Electron.
What we can:
- check the updates
- show Release notes on new version
- apply updates on confirmation

This is Default Electron Modal:

image

I think we must use our UI concept in this situation, that's why need to do next:
- Mockups on modal window "New version is Available" (@skylarrichard123 )
- Mockups on Indicator of new version (@skylarrichard123 )

### Update server
@dgca Need choose one of this server and up (if it need) it somewhere

#### [`update-electron-app`](https://github.com/electron/update-electron-app)
**Possitive moments:**
- No need to up server
- All information is get from Github releases
- Easy integration into app

**Negative moments:**
- Worked only with public Github repo
- Cannot customize dialog window
- Cannot customize update behavior
- Cannot provide information about Releases (Release notes)
- Cannot provide information about versions

#### [Hazel](https://github.com/vercel/hazel)
**Possitive moments:**
- Server is up on Versel
- Easy setup of the server on Versel
- All information is get from Github releases
- Provides possibility on full customization of update process

 **Negative moments:**
- Cannot provide information about Releases (Release notes)
- Cannot provide information about versions

#### [Nuts](https://github.com/GitbookIO/nuts)
**Possitive moments:**
- All information is get from Github releases
- Easy setup of the server on Heroku
- Provides possibility on full customization of update process
- Provide information about Releases
- Support pre-release channels

#### [`electron-release-server`](https://github.com/ArekSredzki/electron-release-server)
**Possitive moments:**
- Provides possibility on full customization of update process
- Provide information about Releases
- Support pre-release channels
- Support Docker

 **Negative moments:**
- Need up server somewhere with localstorage
- Need upload releases on server

License - MIT

#### [Nucleus](https://github.com/atlassian/nucleus)
**Possitive moments:**
- Provides possibility on full customization of update process
- Provide information about Releases
- Support pre-release channels
- Support Linux
- Have plugin for `electron-forge`

 **Negative moments:**
- Need up server somewhere with localstorage
- Need upload releases on server

License - Apache 2.0 © Atlassian Pty Ltd

### CODE REVIEW

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
Screen Shot 2023-03-23 at 1 29 31 PM

**Comment by azhurauski-sc** [comment]
Create task in [Linear](https://linear.app/if-labs/issue/IFL-417/add-possibility-to-auto-update-of-application)

**Review by skylarrichard123 — CHANGES_REQUESTED** [review]
changes here:
https://www.figma.com/file/fYw3aNgfS0qCS2jezGqv8P/Wallet-(New-Ui-Kit)?node-id=5364%3A19659&t=ox1Z4LtM42KjMDh7-1

**Comment by azhurauski-sc** [comment]
Fixed remarks. 
For demo data update modal will show up in a 5 minutes, clicking any button on it will not result in any actions.

**Comment by skylarrichard123** [comment]
Screen Shot 2023-04-11 at 10 51 13 AM

**Comment by azhurauski-sc** [comment]
required PR about fetching release notes through hazel.
https://github.com/iron-fish/wallet-app-update-server/pull/1

**Review by azhurauski-sc — APPROVED** [review]

**Pull request merged**
